-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cache
(
    key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default" NOT NULL,
    expiration integer NOT NULL,
    CONSTRAINT cache_pkey PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS public.cache_locks
(
    key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    owner character varying(255) COLLATE pg_catalog."default" NOT NULL,
    expiration integer NOT NULL,
    CONSTRAINT cache_locks_pkey PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS public.comentarios_proyecto
(
    cop_codigo bigserial NOT NULL,
    cop_descripcion text COLLATE pg_catalog."default" NOT NULL,
    pry_codigo bigint NOT NULL,
    uex_codigo bigint,
    cop_nombre_contacto character varying(255) COLLATE pg_catalog."default",
    cop_fecha_creacion timestamp(0) without time zone,
    CONSTRAINT comentarios_proyecto_pkey PRIMARY KEY (cop_codigo)
);

CREATE TABLE IF NOT EXISTS public.componente_programa
(
    cpp_codigo bigserial NOT NULL,
    comp_codigo bigint NOT NULL,
    pro_codigo integer NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    tra_codigo character varying(10) COLLATE pg_catalog."default",
    cantidad integer DEFAULT 1,
    CONSTRAINT componente_programa_pkey PRIMARY KEY (cpp_codigo),
    CONSTRAINT comp_prog_tra_unique UNIQUE (comp_codigo, pro_codigo, tra_codigo)
);

CREATE TABLE IF NOT EXISTS public.componentes
(
    comp_codigo bigserial NOT NULL,
    comp_nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    coord_codigo bigint,
    comp_anio character varying(32) COLLATE pg_catalog."default",
    comp_es_obligatorio boolean NOT NULL DEFAULT true,
    comp_estado_logico boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    comp_tipo_archivo character varying(100) COLLATE pg_catalog."default",
    comp_tamano_maximo_mb integer,
    CONSTRAINT componentes_pkey PRIMARY KEY (comp_codigo)
);

CREATE TABLE IF NOT EXISTS public.comunidad_estudiante
(
    com_codigo bigint NOT NULL,
    est_cedula character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT comunidad_estudiante_pkey PRIMARY KEY (com_codigo, est_cedula)
);

CREATE TABLE IF NOT EXISTS public.comunidades
(
    com_codigo bigserial NOT NULL,
    com_nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    com_direccion text COLLATE pg_catalog."default",
    com_rif character varying(255) COLLATE pg_catalog."default",
    com_correo character varying(255) COLLATE pg_catalog."default",
    com_dir_codigo integer,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    com_telefono character varying(50) COLLATE pg_catalog."default",
    com_estado_logico boolean NOT NULL DEFAULT true,
    CONSTRAINT comunidades_pkey PRIMARY KEY (com_codigo)
);

CREATE TABLE IF NOT EXISTS public.direcciones
(
    dir_codigo bigserial NOT NULL,
    mun_codigo bigint NOT NULL,
    dir_parroquia character varying(255) COLLATE pg_catalog."default" NOT NULL,
    dir_sector character varying(255) COLLATE pg_catalog."default" NOT NULL,
    dir_calle character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT direcciones_pkey PRIMARY KEY (dir_codigo)
);

CREATE TABLE IF NOT EXISTS public.estados
(
    est_codigo bigserial NOT NULL,
    est_nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT estados_pkey PRIMARY KEY (est_codigo)
);

CREATE TABLE IF NOT EXISTS public.failed_jobs
(
    id bigint NOT NULL,
    uuid character varying(255) COLLATE pg_catalog."default" NOT NULL,
    connection text COLLATE pg_catalog."default" NOT NULL,
    queue text COLLATE pg_catalog."default" NOT NULL,
    payload text COLLATE pg_catalog."default" NOT NULL,
    exception text COLLATE pg_catalog."default" NOT NULL,
    failed_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT failed_jobs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.grupo_proyecto_modulo
(
    grp_codigo bigserial NOT NULL,
    grp_nombre character varying(120) COLLATE pg_catalog."default" NOT NULL,
    grp_contexto text COLLATE pg_catalog."default",
    grp_com_codigo bigint,
    grp_creador_cedula character varying(20) COLLATE pg_catalog."default",
    grp_miembros text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    grp_estado_logico boolean NOT NULL DEFAULT true,
    grp_identificador character varying(120) COLLATE pg_catalog."default",
    estado_logico boolean NOT NULL DEFAULT true,
    CONSTRAINT grupo_proyecto_modulo_pkey PRIMARY KEY (grp_codigo)
);

CREATE TABLE IF NOT EXISTS public.involucrado_rol
(
    id bigserial NOT NULL,
    proyecto_involucrado_id bigint NOT NULL,
    rol_id bigint NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT involucrado_rol_pkey PRIMARY KEY (id),
    CONSTRAINT involucrado_rol_unique UNIQUE (proyecto_involucrado_id, rol_id)
);

CREATE TABLE IF NOT EXISTS public.involucrados
(
    id bigserial NOT NULL,
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    apellido character varying(150) COLLATE pg_catalog."default" NOT NULL,
    cedula character varying(20) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT involucrados_pkey PRIMARY KEY (id),
    CONSTRAINT involucrados_cedula_unique UNIQUE (cedula)
);

CREATE TABLE IF NOT EXISTS public.job_batches
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    total_jobs integer NOT NULL,
    pending_jobs integer NOT NULL,
    failed_jobs integer NOT NULL,
    failed_job_ids text COLLATE pg_catalog."default" NOT NULL,
    options text COLLATE pg_catalog."default",
    cancelled_at integer,
    created_at integer NOT NULL,
    finished_at integer,
    CONSTRAINT job_batches_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.jobs
(
    id bigint NOT NULL,
    queue character varying(255) COLLATE pg_catalog."default" NOT NULL,
    payload text COLLATE pg_catalog."default" NOT NULL,
    attempts smallint NOT NULL,
    reserved_at integer,
    available_at integer NOT NULL,
    created_at integer NOT NULL,
    CONSTRAINT jobs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.linea_investigacions
(
    lin_codigo bigserial NOT NULL,
    lin_nombre_investigacion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    lin_descripcion text COLLATE pg_catalog."default",
    lin_area_de_investigacion character varying(255) COLLATE pg_catalog."default" NOT NULL,
    coord_codigo bigint,
    lin_estado linea_investigacions_lin_estado_enum DEFAULT 'Activo'::linea_investigacions_lin_estado_enum,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT linea_investigacions_pkey PRIMARY KEY (lin_codigo)
);

CREATE TABLE IF NOT EXISTS public.metodologia_investigacions
(
    mei_codigo bigserial NOT NULL,
    mei_nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    mei_descripcion text COLLATE pg_catalog."default",
    mei_estado_logico boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT metodologia_investigacions_pkey PRIMARY KEY (mei_codigo)
);

CREATE TABLE IF NOT EXISTS public.migrations
(
    id serial NOT NULL,
    migration character varying(255) COLLATE pg_catalog."default" NOT NULL,
    batch integer NOT NULL,
    CONSTRAINT migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.municipios
(
    mun_codigo bigserial NOT NULL,
    est_codigo bigint NOT NULL,
    mun_nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT municipios_pkey PRIMARY KEY (mun_codigo)
);

CREATE TABLE IF NOT EXISTS public.objetivo_investigacions
(
    obi_codigo bigserial NOT NULL,
    obi_nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    obi_descripcion text COLLATE pg_catalog."default",
    obi_estado_logico boolean NOT NULL DEFAULT true,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT objetivo_investigacions_pkey PRIMARY KEY (obi_codigo)
);

CREATE TABLE IF NOT EXISTS public.password_reset_tokens
(
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone,
    CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS public.proyecto_documentos
(
    pd_codigo bigserial NOT NULL,
    pry_codigo bigint NOT NULL,
    pd_archivo_path character varying(500) COLLATE pg_catalog."default" NOT NULL,
    pd_orden integer NOT NULL DEFAULT 0,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    comp_codigo bigint NOT NULL,
    pd_estado integer NOT NULL DEFAULT 0,
    pd_observacion text COLLATE pg_catalog."default",
    CONSTRAINT proyecto_documentos_pkey PRIMARY KEY (pd_codigo)
);

COMMENT ON COLUMN public.proyecto_documentos.pd_estado
    IS '0:pendiente, 1:aceptado, 2:rechazado';

CREATE TABLE IF NOT EXISTS public.proyecto_involucrado
(
    id bigserial NOT NULL,
    proyecto_id bigint NOT NULL,
    involucrado_id bigint NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT proyecto_involucrado_pkey PRIMARY KEY (id),
    CONSTRAINT idx_pi_unique UNIQUE (proyecto_id, involucrado_id)
);

CREATE TABLE IF NOT EXISTS public.proyectos
(
    pry_codigo bigserial NOT NULL,
    com_codigo bigint,
    aud_codigo bigint,
    pry_resumen text COLLATE pg_catalog."default" NOT NULL,
    pry_direccion_logica character varying(255) COLLATE pg_catalog."default",
    lin_codigo bigint,
    mei_codigo bigint,
    tin_codigo bigint,
    pry_uex_codigo integer,
    pry_estado_logico boolean NOT NULL DEFAULT true,
    pry_motivo_rechazo text COLLATE pg_catalog."default",
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    pry_estado_validacion character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Pendiente'::character varying,
    pry_actualizado_por_estudiante boolean NOT NULL DEFAULT false,
    pry_fecha_actualizacion_estudiante timestamp(0) without time zone,
    pry_creador_cedula character varying(20) COLLATE pg_catalog."default",
    pry_inc_codigo bigint,
    obj_codigo bigint,
    obi_codigo bigint,
    objetivo_investigacion_id bigint,
    pry_cantidad_beneficiados integer,
    CONSTRAINT proyectos_pkey PRIMARY KEY (pry_codigo)
);

CREATE TABLE IF NOT EXISTS public.proyectos_publicados
(
    pub_codigo bigserial NOT NULL,
    pry_codigo bigint NOT NULL,
    pub_archivo_path character varying(500) COLLATE pg_catalog."default",
    pub_estado character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'publicado'::character varying,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT proyectos_publicados_pkey PRIMARY KEY (pub_codigo)
);

CREATE TABLE IF NOT EXISTS public.rol_externo
(
    rex_codigo integer NOT NULL,
    rex_nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT rol_externo_pkey PRIMARY KEY (rex_codigo)
);

CREATE TABLE IF NOT EXISTS public.roles_involucrados
(
    id bigint NOT NULL DEFAULT nextval('roles_catalogo_id_seq'::regclass),
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT roles_catalogo_pkey PRIMARY KEY (id),
    CONSTRAINT idx_rc_nombre UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.sessions
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id bigint,
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    payload text COLLATE pg_catalog."default" NOT NULL,
    last_activity integer NOT NULL,
    CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tipo_investigacions
(
    tin_codigo bigserial NOT NULL,
    tin_nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tin_descripcion text COLLATE pg_catalog."default",
    tin_estado_logico boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT tipo_investigacions_pkey PRIMARY KEY (tin_codigo)
);

CREATE TABLE IF NOT EXISTS public.titulos_vinculacion
(
    tiv_codigo bigserial NOT NULL,
    tiv_titulo text COLLATE pg_catalog."default" NOT NULL,
    tiv_estado_logico boolean NOT NULL DEFAULT true,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    CONSTRAINT titulos_vinculacion_pkey PRIMARY KEY (tiv_codigo)
);

CREATE TABLE IF NOT EXISTS public.usuarios_externos
(
    uex_codigo integer NOT NULL,
    uex_nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    uex_contrasena character varying(255) COLLATE pg_catalog."default" NOT NULL,
    uex_rex_codigo integer,
    uex_estado usuarios_externos_uex_estado_enum DEFAULT 'Activo'::usuarios_externos_uex_estado_enum,
    CONSTRAINT usuarios_externos_pkey PRIMARY KEY (uex_codigo)
);

CREATE TABLE IF NOT EXISTS public.vinculaciones
(
    vin_codigo bigserial NOT NULL,
    pry_codigo bigint NOT NULL,
    vin_tipo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    com_codigo bigint,
    vin_observaciones text COLLATE pg_catalog."default",
    vin_estado_logico boolean NOT NULL DEFAULT true,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    vin_descripcion text COLLATE pg_catalog."default",
    tiv_codigo bigint,
    CONSTRAINT vinculaciones_pkey PRIMARY KEY (vin_codigo)
);

ALTER TABLE IF EXISTS public.componente_programa
    ADD CONSTRAINT componente_programa_comp_codigo_foreign FOREIGN KEY (comp_codigo)
    REFERENCES public.componentes (comp_codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS componente_programa_comp_codigo_index
    ON public.componente_programa(comp_codigo);


ALTER TABLE IF EXISTS public.comunidad_estudiante
    ADD CONSTRAINT comunidad_estudiante_comunidad_id_foreign FOREIGN KEY (com_codigo)
    REFERENCES public.comunidades (com_codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    DEFERRABLE;


ALTER TABLE IF EXISTS public.direcciones
    ADD CONSTRAINT direcciones_mun_codigo_foreign FOREIGN KEY (mun_codigo)
    REFERENCES public.municipios (mun_codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    DEFERRABLE;


ALTER TABLE IF EXISTS public.municipios
    ADD CONSTRAINT municipios_est_codigo_foreign FOREIGN KEY (est_codigo)
    REFERENCES public.estados (est_codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    DEFERRABLE;


ALTER TABLE IF EXISTS public.proyecto_documentos
    ADD CONSTRAINT proyecto_documentos_comp_codigo_foreign FOREIGN KEY (comp_codigo)
    REFERENCES public.componentes (comp_codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS proyecto_documentos_comp_codigo_index
    ON public.proyecto_documentos(comp_codigo);


ALTER TABLE IF EXISTS public.proyecto_documentos
    ADD CONSTRAINT proyecto_documentos_pry_codigo_foreign FOREIGN KEY (pry_codigo)
    REFERENCES public.proyectos (pry_codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS proyecto_documentos_pry_codigo_index
    ON public.proyecto_documentos(pry_codigo);


ALTER TABLE IF EXISTS public.proyectos
    ADD CONSTRAINT proyectos_comunidad_id_foreign FOREIGN KEY (com_codigo)
    REFERENCES public.comunidades (com_codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE;
CREATE INDEX IF NOT EXISTS proyectos_com_codigo_index
    ON public.proyectos(com_codigo);


ALTER TABLE IF EXISTS public.proyectos
    ADD CONSTRAINT proyectos_linea_investigacion_id_foreign FOREIGN KEY (lin_codigo)
    REFERENCES public.linea_investigacions (lin_codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE;


ALTER TABLE IF EXISTS public.proyectos
    ADD CONSTRAINT proyectos_metodologia_id_foreign FOREIGN KEY (mei_codigo)
    REFERENCES public.metodologia_investigacions (mei_codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE;


ALTER TABLE IF EXISTS public.proyectos
    ADD CONSTRAINT proyectos_objetivo_investigacion_id_foreign FOREIGN KEY (objetivo_investigacion_id)
    REFERENCES public.objetivo_investigacions (obi_codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.proyectos
    ADD CONSTRAINT proyectos_tipo_investigacion_id_foreign FOREIGN KEY (tin_codigo)
    REFERENCES public.tipo_investigacions (tin_codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE;


ALTER TABLE IF EXISTS public.proyectos
    ADD CONSTRAINT proyectos_usuario_externo_id_foreign FOREIGN KEY (pry_uex_codigo)
    REFERENCES public.usuarios_externos (uex_codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE;


ALTER TABLE IF EXISTS public.proyectos_publicados
    ADD CONSTRAINT proyectos_publicados_proyecto_id_foreign FOREIGN KEY (pry_codigo)
    REFERENCES public.proyectos (pry_codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    DEFERRABLE;


ALTER TABLE IF EXISTS public.usuarios_externos
    ADD CONSTRAINT usuarios_rol_externo_id_foreign FOREIGN KEY (uex_rex_codigo)
    REFERENCES public.rol_externo (rex_codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE;

END;